lightmeet/lightmeet/urls.py
from django.contrib import admin
from django.urls import path, include  # Ajoutez include pour inclure les URLs
from django.conf import settings
from django.conf.urls.static import static
from partner_meet.views import *
from accounts.views import *
from legal.views import *
from psy.views import *
from support.views import *
from posts.views import *
from django.conf.urls.i18n import i18n_patterns  # Pour gérer les patterns i18n

# URL pour le changement de langue
urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # Pour gérer le changement de langue
]

# URLs avec la gestion des langues
urlpatterns += i18n_patterns(
    # Administrateur :
    path('lightmeet-admin/', admin.site.urls),

    path('<str:lang>/rencontres/', PartnerMeetListView.as_view(), name='partner_list'),


    # robots.txt path below
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

    # Page principale francais - anglais - espagnol / CTA Comparer
    path('', Home.as_view(), name="Home"),

    # Support
    path('support', SupportContact, name="Support"),
    path('support/Thanks', SupportContact, name="Support-merci"),

    # Legal
    path('legal/mentions_legales/', LegalControlML.as_view(), name="legal_mentions_legales"),
    path('legal/conditions_generales_utilisation', LegalControlCGU.as_view(), name="legal_CGU"),
    path('legal/politique_de_confidentialite/', LegalControlPDC.as_view(), name="legal_PDC"),
    path('legal/politique_de_cookies/', LegalControlPC.as_view(), name="legal_PC"),
    path('legal/mentions_legales/create/', LegalCreate.as_view(), name="legal_create"),
    path('legal/mentions_legales/<str:slug>/', LegalDetail.as_view(), name="legal_detail"),
    path('legal/mentions_legales/edit/<str:slug>/', LegalUpdate.as_view(), name="legal_edit"),
    path('legal/mentions_legales/delete/<str:slug>/', LegalDelete.as_view(), name="legal_delete"),

    # Partner_meet
    path('valid/', enregistrer_visiteur, name="consentement_visiteur"),
    path('rencontres/', PartnerMeetHome.as_view(), name="recherche_home"),
    path('recherche/create/', PartnerMeetCreate.as_view(), name="recherche_create"),
    path('recherche/<int:pk>/', PartnerMeetDetail.as_view(), name="recherche_detail"),
    path('recherche/edit/<int:pk>/', PartnerMeetUpdate.as_view(), name="recherche_edit"),
    path('recherche/delete/<int:pk>/', PartnerMeetDelete.as_view(), name="recherche_delete"),
    path('recherche/site_de_rencontres/', PartnerMeetBestSite.as_view(), name="recherche_meilleur_site"),  # nouveau

    path('rencontres_adultes/', PartnerMeetHome_Adulte.as_view(), name="recherche_home_adulte"),
    path('recherche/site_de_rencontres_adulte/', PartnerMeetBestSite_Adulte.as_view(), name="recherche_meilleur_site_adulte"),

    # Psy
    #path('therapeutes/', PsyMeetHome.as_view(), name="recherche_therapeutes"),
    #path('psy/create', PsyCreate.as_view(), name="psy_create"),
    #path('psy/<str:slug>', PsyDetail.as_view(), name="psy_detail"),
    #path('psy/edit/<str:slug>', PsyUpdate.as_view(), name="psy_edit"),
    #path('psy/delete/<str:slug>', PsyDelete.as_view(), name="psy_delete"),
    #path('recherche/sites_des_thérapeutes/', PsyMeetBestSite.as_view(), name="recherche_meilleur_therapeutes"),  # nouveau

    # Blog
    path('blog/First_Article', BlogPost1.as_view(), name="1_Blog_Article"),
    path('blog/Second_Article', BlogPost2.as_view(), name="2_Blog_Article"),
    path('blog/Third_Article', BlogPost3.as_view(), name="3_Blog_Article"),
    path('blog/Fourth_Article', BlogPost4.as_view(), name="4_Blog_Article"),
    path('blog/Fifth_Article', BlogPost5.as_view(), name="5_Blog_Article"),
    path('blog/Sixth_Article', BlogPost6.as_view(), name="6_Blog_Article"),
    path('blog/Seventh_Article', BlogPost7.as_view(), name="7_Blog_Article"),
    path('blog/Eighth_Article', BlogPost8.as_view(), name="8_Blog_Article"),
    path('blog/Ninth_Article', BlogPost9.as_view(), name="9_Blog_Article"),
    path('blog/Tenth_Article', BlogPost10.as_view(), name="10_Blog_Article"),
    path('blog/Eleventh_Article', BlogPost11.as_view(), name="11_Blog_Article"),
    path('blog/Twelfth_Article', BlogPost12.as_view(), name="12_Blog_Article"),
    path('blog/Thirteenth_Article', BlogPost13.as_view(), name="13_Blog_Article"),
    path('blog/Fourteenth_Article', BlogPost14.as_view(), name="14_Blog_Article"),
    path('blog/menu', BlogPostHome.as_view(), name="blog_home"),
    path('blog/create', BlogPostCreate.as_view(), name="blog_create"),
    path('blog/<str:slug>', BlogPostDetail.as_view(), name="blog_detail"),
    path('blog/edit/<str:slug>', BlogPostUpdate.as_view(), name="blog_edit"),
    path('blog/delete/<str:slug>', BlogPostDelete.as_view(), name="blog_delete"),
    # Tout ce qui est statique, comme les images et fichiers médias
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# the original is this one

# from django.contrib import admin
# from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
# from partner_meet.views import *
# from accounts.views import *
# from legal.views import *
# from psy.views import *
# from support.views import *
# from posts.views import *
# from django.conf.urls.i18n import i18n_patterns

# #urlpatterns = [
# #    path('i18n/', include('django.conf.urls.i18n')),  # Pour gérer le changement de langue
# #] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     # Administrateur :
#     path('lightmeet-admin/', admin.site.urls),

#     # Page principale francais - anglais - espagnol / CTA Comparer
#     path('', Home.as_view(), name="Home"),
#     #path('en/', Home.as_view(), name="Home"),
#     #path('sp/',Home.as_view(),name="Home"),

#     # Accounts
#     #path('connexion', inscription, name="Connexion"),
#     #path('connexion/social_network', SocialNetwork, name="Connexion par réseau social"),
#     #path('login', login_view, name="login"),
#     #path('logout', logout_view, name="logout"),
#     #path('connexion/new_account', nouvel_utilisateur, name="nouvel_utilisateur"),
#     #path('connexion/forget_password', forget_password, name="forget_password"),
#     #path('connexion/delete_account', delete_account, name="Delete Account"),

#     # Support
#     path('support', SupportContact, name="Support"),
#     path('support/Thanks', SupportContact, name="Support-merci"),

#     # Legal
#     path('legal/mentions_legales/', LegalControlML.as_view(), name="legal_mentions_legales"),
#     path('legal/conditions_generales_utilisation', LegalControlCGU.as_view(), name="legal_CGU"),
#     path('legal/politique_de_confidentialite/', LegalControlPDC.as_view(), name="legal_PDC"),
#     path('legal/politique_de_cookies/', LegalControlPC.as_view(), name="legal_PC"),
#     path('legal/mentions_legales/create/', LegalCreate.as_view(), name="legal_create"),
#     path('legal/mentions_legales/<str:slug>/', LegalDetail.as_view(), name="legal_detail"),
#     path('legal/mentions_legales/edit/<str:slug>/', LegalUpdate.as_view(), name="legal_edit"),
#     path('legal/mentions_legales/delete/<str:slug>/', LegalDelete.as_view(), name="legal_delete"),

#     # Partner_meet
#     path('valid/', enregistrer_visiteur, name="consentement_visiteur"),
#     path('rencontres/', PartnerMeetHome.as_view(), name="recherche_home"),
#     path('recherche/create/', PartnerMeetCreate.as_view(), name="recherche_create"),
#     path('recherche/<int:pk>/', PartnerMeetDetail.as_view(), name="recherche_detail"),
#     path('recherche/edit/<int:pk>/', PartnerMeetUpdate.as_view(), name="recherche_edit"),
#     path('recherche/delete/<int:pk>/', PartnerMeetDelete.as_view(), name="recherche_delete"),
#     path('recherche/site_de_rencontres/', PartnerMeetBestSite.as_view(), name="recherche_meilleur_site"),  # nouveau

#     # Psy
#     path('therapeutes/', PsyMeetHome.as_view(), name="recherche_therapeutes"),
#     path('psy/create', PsyCreate.as_view(), name="psy_create"),
#     path('psy/<str:slug>', PsyDetail.as_view(), name="psy_detail"),
#     path('psy/edit/<str:slug>', PsyUpdate.as_view(), name="psy_edit"),
#     path('psy/delete/<str:slug>', PsyDelete.as_view(), name="psy_delete"),
#     path('recherche/sites_des_thérapeutes/', PsyMeetBestSite.as_view(), name="recherche_meilleur_therapeutes"),  # nouveau

#     # Blog
#     path('blog/main_article',BlogPost1.as_view(), name="blog_home_1"),
#     path('blog/second_article',BlogPost2.as_view(), name="blog_home_2"),
#     path('blog/menu',BlogPostHome.as_view(), name="blog_home"),
#     path('blog/create', BlogPostCreate.as_view(), name="blog_create"),
#     path('blog/<str:slug>', BlogPostDetail.as_view(), name="blog_detail"),
#     path('blog/edit/<str:slug>', BlogPostUpdate.as_view(), name="blog_edit"),
#     path('blog/delete/<str:slug>', BlogPostDelete.as_view(), name="blog_delete"),

# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lightmeet/support/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class SupportTicket(models.Model):

    sender_email = models.EmailField(verbose_name=_("Adresse e-mail de l'expéditeur"))

    SUJET = (
        ("Informations", _("Je souhaite en savoir plus")),
        ("Partenariat", _("Je cherche à réaliser un partenariat")),
        ("Technique", _("Soucis technique sur la plateforme")),
    )
    subject = models.CharField(choices=SUJET, max_length=25, default='', verbose_name=_("Sujet"))
    message = models.TextField(verbose_name=_("Message"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Date de création"))

    def __str__(self):
        return f"{self.subject} - {self.sender_email}"

    class Meta:
        verbose_name = _("Contact avec le client")
        verbose_name_plural = _("Contacts avec les clients")

lightmeet/support/forms.py
from django.forms import ModelForm
from django import forms
from support.models import *


# Formulaire basé sur le modèle SupportTicket
class SupportTicketForm(ModelForm):
    required_css_class = "required_field"

    sender_email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": " Adresse e-mail *"
        })
    )

    subject = forms.ChoiceField(
        required=True,
        choices=SupportTicket.SUJET,
        widget=forms.Select(attrs={
            "class": "form-control",
            "placeholder": "Le sujet de ton choix *"
        })
    )

    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "placeholder": " Contenu du message *"
        })
    )

    class Meta:
        model = SupportTicket
        fields = ['sender_email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sender_email'].label = ''
        self.fields['subject'].label = ''
        self.fields['message'].label = ''

lightmeet/support/views.py
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _  # Importez gettext_lazy pour les chaînes traduisibles
from support.models import SupportTicket
from support.forms import SupportTicketForm
from django.shortcuts import render

class ContactSubscribe(TemplateView):
    model = SupportTicket
    template_name = ("support/base_Support.html")  # Utilisez gettext_lazy ici pour les chemins de template

class ContactSubscribe_2(TemplateView):
    model = SupportTicket
    template_name = ("support/Support.html")  # Utilisez gettext_lazy ici pour les chemins de template

class ContactSubscribe_3(TemplateView):
    model = SupportTicket
    template_name = ("support/Thanks.html")  # Utilisez gettext_lazy ici pour les chemins de template

def SupportContact(request):
    if request.method == "POST":
        form = SupportTicketForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, ("support/Thanks.html"), context={"form": form})  # Utilisez gettext_lazy ici pour le chemin du template
    else:
        form = SupportTicketForm()
    return render(request, ("support/Support.html"), context={"form": form})  # Utilisez gettext_lazy ici pour le chemin du template

lightmeet/support/templates/support/Support.html
{% extends 'support/base_Support.html' %}
{% load static %}
{% load i18n %}
<head>
    <title>{% 'trans Contactez notre équipe de support' % } - Lightmeet </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Contactez notre équipe de support pour toute question ou préoccupation. Remplissez le formulaire ci-dessous et nous vous répondrons rapidement.">
    <meta name="author" content="Lightmeet">
    <link rel="canonical" href="https://www.lightmeet.fr/fr/support">

    {% load static %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'partner_meet/css/style_base.css' %}">
        <link rel="stylesheet" href="{% static 'support/css/contact.css' %}">
    {% endblock %}
</head>
<body>
    {% block section %}
    <section class="ContainerSupport">
        <h1 class="Title">{% trans 'Contactez notre équipe de support' %}</h1>
        <p class="subTitle">{% trans 'Utilisez le formulaire ci-dessous pour nous envoyer un message' %}</p>

        <p style="text-align: justify;"> {% trans "Si vous avez des questions ou des préoccupations, n'hésitez pas à nous contacter. Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais." %}</p>

        <form class="form" method="POST" aria-labelledby="contact-form">
            {% csrf_token %}

            <div class="Apellation">
                <label for="id_sender_email">{% trans 'Votre e-mail :' %}</label>
                {{ form.sender_email }}
            </div>

            <div class="Apellation2">
                <label for="id_subject">{% trans 'Sujet :' %}</label>
                {{ form.subject }}
            </div>

            <div class="Apellation3">
                <label for="id_message">{% trans 'Votre message :' %}</label>
                {{ form.message }}
            </div>

            <input class="SendMessage" type="submit" value="Envoyer" aria-label="Envoyer le message">
        </form>

        <p style="text-align: justify;"> {% trans 'Nous nous engageons à vous répondre rapidement. Consultez notre' %}<a href="{% url 'Home' %}">FAQ</a> {% trans 'pour des réponses immédiates à vos questions courantes.' %}</p>
    </section>
    {% endblock %}
</body>
</html>

lightmeet/support/templates/support/Thanks.html
{% extends 'support/base_Support.html' %}
{% load static %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Contactez notre équipe de support pour toute question ou préoccupation. Remplissez le formulaire ci-dessous et nous vous répondrons rapidement.">
    <meta name="keywords" content="contact, support, formulaire de contact, aide, questions fréquentes, Lightmeet">
    <meta name="author" content="Votre Nom ou Votre Entreprise">
    <link rel="canonical" href="https://www.votresite.com/contact">

    {% block css %}
        <link rel="stylesheet" href="{% static 'partner_meet/css/style_base.css' %}">
        <link rel="stylesheet" href="{% static 'support/css/contact.css' %}">
        <!--il y avait un bug quand il y a 2 block de css qui se suivent comme le cas d'avant-->
        <link rel="stylesheet" href="{% static 'support/css/style_3.css' %}">
        <link rel="stylesheet" href="{% static 'partner_meet/css/style_base.css' %}">
    {% endblock %}
</head>



{% block section %}
<section>
    <img class="Purple" src="{% static 'support/Logos/Purple.png' %}" style="position:absolute;z-index:10;width:100%;height:83%;">
    <div class="Title">{% trans 'Votre message a bien été envoyé.' %} </div>
    <img class="Letter" src="{% static 'support/Logos/Letter.png' %}" opacity="0.7">
    <div class="Remerciements" style="font-size: 14px;">{% trans "L’équipe LightMeet vous répondra dans les plus brefs délais." %}</div>
    <div class="Suivi_1">{% trans "Restez connecté, des nouvelles du lancement vous seront prochainement envoyées par e-mail !" %}</div>
    <div class="Suivi_2">{% trans 'En attendant, suivez-nous sur les réseaux sociaux :' %}</div>
    <div class="Network" style="display:flex;flex-direction:row;justify-content:space-evenly;text-align:center;align-items:center;z-index:200;">
        <a href="https://www.instagram.com/lightmeet.fr/">
            <div>
                <img style="margin:12px;z-index:100;text-align:center;align-items:center;" src="{% static 'support/Logos/Instagram.png' %}" width="30px" height="30px">
            </div>
        </a>
        <a href="https://www.linkedin.com/in/micka%C3%ABl-boudengen-4ba351131/">
            <div>
                <img style="margin:12px;z-index:100;text-align:center;align-items:center;" src="{% static 'support/Logos/LinkedIn.png' %}" width="30px" height="30px">
            </div>
        </a>
    </div>
</section>
{% endblock %}

lightmeet/support/templates/support/base_Support.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="LightMeet, le premier comparateur de sites de rencontres.">
    <title>LightMeet - Support</title>

    {% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'partner_meet/css/style_base.css' %}">
    {% endblock %}
    <link rel="icon" type="image/png" href="{% static 'partner_meet/Logos/L2M.png' %}">
<link rel="canonical" href="https://www.lightmeet.fr/fr/rencontres">
    <meta name="author" content="Lightmeet">
    <meta name="robots" content="index, follow">

    <!-- Hotjar Tracking -->
    <script defer>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:4960613,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

    <!-- Visitor Tracking -->
    <script defer src='https://app.visitortracking.com/assets/js/tracer.js'></script>
    <script defer>
        function init_tracer() {
            var tracer = new Tracer({
                websiteId : "bf6d09fc-7223-4dba-a994-36a534160065",
                async : true,
                debug : false
            });
        }
    </script>
</head>

<body class="container">
    <header>
        <a href="{% url 'Home' %}" class="ListeHeader">
            <img class="LightMeetLogo" src="{% static 'partner_meet/Logos/LightMeet.svg' %}" alt="Logo LightMeet">
        </a>
        <nav class="navPos">
            <button style="color:black; background-color:#FBF1D6; padding: 9px 55px;border: 0.1px solid grey;border-radius:50px; cursor: pointer; font-size: 12px;"
                onclick="window.location.href='{% url 'recherche_home_adulte' %}'">
                {% trans '+ 18 ans' %}
            </button>
            <a href="{% url 'blog_home' %}" class="ListeHeader">Blog</a>
            <a href="{% url 'Support' %}" class="ListeHeader">Contact</a>
        </nav>
        <nav class="navHeader">
            <div class="menuHamburger">
                <div class="line Line1"></div>
                <div class="line Line2"></div>
                <div class="line Line3"></div>
            </div>
            <ul class="navMenu">
                <li><a href="{% url 'recherche_home' %}" class="ListeHeader">Site de rencontres</a></li>
                <li><a href="{% url 'blog_home' %}" class="ListeHeader">Blog</a></li>
                <li><a href="{% url 'Home' %}" class="ListeHeader">FAQ</a></li>
                <li><a href="{% url 'Support' %}" class="ListeHeader">Support</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}{% endblock %}
    {% block aside %}{% endblock %}
    {% block section %}{% endblock %}

    {% block footer %}
    <footer>
        <div class="footerPc">
            <ul class="ListFooter">
                <li><a class="linkFooter" href="{% url 'Home' %}">® 2025 Lightmeet</a></li>
                <li><a class="linkFooter" href="{% url 'legal_mentions_legales' %}">Mentions légales</a></li>
                <li><a class="linkFooter" href="{% url 'legal_PDC' %}">Politique de confidentialité</a></li>
                <li><a class="linkFooter" href="{% url 'legal_CGU' %}">Conditions générales d'utilisation</a></li>
                <li><a class="linkFooter" href="{% url 'legal_PC' %}">Politique de Cookies</a></li>
            </ul>
        </div>
    </footer>
    {% endblock %}

    <script>
        document.querySelector('.menuHamburger').addEventListener('click', function () {
            this.classList.toggle('active');
            document.querySelector('.navMenu').classList.toggle('active');
            document.body.style.overflow = document.querySelector('.navMenu').classList.contains('active') ? 'hidden' : '';
        });
    </script>
</body>
</html>